default_agent: my_agent
agents:
  my_agent:
    name: my_agent
    entrypoint: /home/toyofumi/Project/knowledge-share-app-gen1/agentcore/my_agent.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/toyofumi/Project/knowledge-share-app-gen1/agentcore
    aws:
      execution_role: arn:aws:iam::832780067678:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-1-e72c1a7c7a
      execution_role_auto_create: false
      account: '832780067678'
      region: ap-northeast-1
      ecr_repository: 832780067678.dkr.ecr.ap-northeast-1.amazonaws.com/bedrock-agentcore-my_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: my_agent-8ihNxq5pN4
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-1:832780067678:runtime/my_agent-8ihNxq5pN4
      agent_session_id: 26a1f0be-d4e0-4930-9c43-56ce033e8678
    codebuild:
      project_name: bedrock-agentcore-my_agent-builder
      execution_role: arn:aws:iam::832780067678:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-northeast-1-e72c1a7c7a
      source_bucket: bedrock-agentcore-codebuild-sources-832780067678-ap-northeast-1
    memory:
      mode: STM_AND_LTM
      memory_id: my_agent_mem-S18JfcBQcc
      memory_arn: null
      memory_name: my_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_dMnUK5rLo/.well-known/openid-configuration
        allowedClients:
        - 2danloh9bnkjqdjmct4ls2nv1j
    request_header_configuration: null
    oauth_configuration: null
